void Disptxt(char text[] , int nbchar);
void Color(int Texte,int Fond);
void Disp(int stage[8][8]);
void Game(int stage[8][8]);
int Move(int stage[8][8]);
void Motherboard2();
void WhichEnemie();
int Alea(int luck);
void Motherboard();
void start_virus();
void Chargement();
void Inventory();
void Character();
void Inventory();
void end_game();
void Position();
void Gameover();
void Back_pro();
void Darkpix();
void Cor_mem();
void Option();
void Screen();
void Artif();
void Virus();
void getch();
void heal();
int Fight();
void BIOS();
void Save();
void Boss();
void Help();
void Loot();
void New();
void RAM();
void HDD();
void GPU();
int Menu();